name: Fork sync from upstream
on:
  schedule:
    - cron:  '0 7 * * *'
    # scheduled at 07:00 every day

  workflow_dispatch:  # click the button on Github repo!

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.5
        with:
          github_token: ${{ secrets.SYNC_TOKEN }} # 这个 token action 会默认配置, 这里只需这样写就行
          owner: anncwb # fork 上游项目 owner
          head: main # fork 上游项目需要同步的分支
          base: main # 需要同步到本项目的目标分支
